__NumPy:__

numpy is a linear algebra library for python. almost all of the libraries in Pydata ecosystem relies on Numpy as their main building block

it is fast as it has bindings to C library

if it is not installed in your system use below commands to get it which resolves all its dependencies

__conda install numpy__(if using anaconda distribution)

__pip install numpy__(otherwise)

__numpy arrays :__

In [ ]:
#creating numpy arrays from lists
my_list=[1,2,3,4]
my_list

In [2]:
import numpy as np #np is a name can give anything i used np short for numpy


In [3]:
np.array(my_list)

array([1, 2, 3, 4])

we can store it in a variable as below

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4])

notice single [] denotes its a vector (single dimension array)

two dimensional array from lists:-

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

notice two [[ at the start of the array denoting its a two dimensional array

__array creation without lists__

In [12]:
np.arange(1,9) #arange works just like range function start stop and step

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [14]:
#array of zeroes
np.zeros(4) #will be a single dimension array with 4 columns all 0

array([0., 0., 0., 0.])

In [15]:
np.zeros((2,3)) #will be a two dimensional with 2 rows 3 columns. used a tuple for this

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#similarly array of ones
np.ones(4) #single dimensional

array([1., 1., 1., 1.])

In [17]:
np.ones((2,3)) # two dimensional

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2,3,4)) #can also be three dimensional 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

__the identity matrix__

In [19]:
np.eye(3) # takes only one param

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

__linspace :__ a builtin function that returns evenly spaced numbers over a specified interval

In [20]:
np.linspace(0,5,10) #start stop number of points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

10 evenly spaced numbers between 0 and 5.  dont get confused with arange and linspace. arange gives integer after step size.

In [21]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

looks like a 2D array but is a 1D notice only one [ at start and end

__arrays of random numbers:__

In [22]:
np.random.rand(5) #gives 5 random numbers of uniform distribution over 0 to 1

array([0.35241864, 0.10180229, 0.43856585, 0.83172353, 0.77252522])

In [23]:
#for 2D use , instead of tuples here in random arrays
np.random.rand(5,5)

array([[0.84247525, 0.03105831, 0.95734384, 0.47253567, 0.5036808 ],
       [0.93737712, 0.15491362, 0.51207785, 0.4160138 , 0.46589832],
       [0.03278226, 0.59315439, 0.49593388, 0.18989076, 0.61736848],
       [0.67313483, 0.89721349, 0.59205374, 0.6466057 , 0.81145004],
       [0.74273019, 0.55387821, 0.40472211, 0.62317038, 0.76200379]])

In [24]:
np.random.randn(5) #gives 5 random numbers of normal/gaussian distribution centered around 0

array([0.60932991, 0.3644616 , 1.84510513, 2.69864543, 0.05119397])

In [25]:
np.random.randn(2,2) #2D

array([[-0.79978807,  0.43662389],
       [ 0.54296544, -0.73393464]])

In [26]:
#randint gives random integers between a low to high
np.random.randint(0,100) #start(inclusive) stop(exclusive) number of sample

99

In [27]:
np.random.randint(0,100,10) #will give 10 random numbers between 0 and 100

array([40, 15,  0, 42, 53, 65, 71, 99, 43, 63])

__attributes and methods on arrays__

In [33]:
arr=np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
rand_arr=np.random.randint(1,10,10)
rand_arr

array([1, 8, 1, 1, 2, 5, 7, 9, 3, 7])

__reshape()__ method reshapes a given array. array values are not changed just dimensions can be changed

In [34]:
arr.reshape(4,4) #turns arr to 4x4 matrix 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

notice contents of arr are same only dimension has changed. however the reshaping should not conflict with the number of elements in the array as below

In [35]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 16 into shape (5,5)

the error is because 5x5 matrix requires 25 items arr has only 16. best way to figure this out is __rows x columns = items in array__

In [36]:
arr.reshape(2,8) #2 x 8 =16(number of items in arr)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

__max() min()__ methods to get max and min values from an array

In [38]:
print rand_arr.max() #gives max value
print rand_arr.min() #gives min value
print rand_arr #print rand_arr to check 

9
1
[1 8 1 1 2 5 7 9 3 7]


so 1 is smallest and 9 is largest in the array

__argmax() argmin():__ methods to index of the max and min items in the array

In [39]:
print rand_arr.argmax() #gives index of max item
print rand_arr.argmin() #gives index of min item
print rand_arr

7
0
[1 8 1 1 2 5 7 9 3 7]


7th index is 9 which is max 0th index is 1 which is min.

__shape__ attribute gives shape of the array

In [40]:
arr.shape

(16,)

denotes its a single dimension array

In [42]:
arr=arr.reshape(4,4)

In [43]:
arr.shape

(4, 4)

denotes its a 2D array

__dtype__ attribute gives data type of the array

In [44]:
arr.dtype

dtype('int64')