__numpy indexing and selection:__

In [1]:
import numpy as np

In [2]:
#creating an array
arr=np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#value at index 4 (its 5 index starts from 0)
arr[4]

5

In [6]:
#value from index 0 to 6
arr[0:7]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[7]

8

see arr[7] is 8 which is not a part in arr[0:7] the stop index is exclusive same as in normal python list

In [9]:
arr[::-1] #reverse the array negative indexing

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

the only way numpy array differs from normal list indexing is that they can be broadcast as below

In [10]:
arr[:5]=15 #make items from index 0 to 4 equals to 15 note :5 is exclusive

In [11]:
arr

array([15, 15, 15, 15, 15,  6,  7,  8,  9, 10])

In [13]:
lst=range(1,11)
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
lst[:5]=15 #cannot be done in normal lists

TypeError: can only assign an iterable

__be carefull about the broadcast if another array is created by slicing an array its just a view of the parent array and any change would also reflect in it as below__

In [23]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_of_arr=arr[:5]
slice_of_arr

array([1, 2, 3, 4, 5])

In [25]:
slice_of_arr[:]=15

In [26]:
slice_of_arr

array([15, 15, 15, 15, 15])

In [27]:
arr

array([15, 15, 15, 15, 15,  6,  7,  8,  9, 10])

any change in slice_of_array also reflect in arr. slice_of_array is actually a view of arr. to copy an array use copy method on numpy array as below

In [29]:
copy_of_arr=arr.copy()
copy_of_arr

array([15, 15, 15, 15, 15,  6,  7,  8,  9, 10])

In [30]:
copy_of_arr[:]=100
copy_of_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr

array([15, 15, 15, 15, 15,  6,  7,  8,  9, 10])

here arr and copy_of_arr are different. changes in copy_of_arr did not reflect in arr. copy_of_arr is actually a copy of arr in memory which has its own elements. its not aview

__indexing a 2D array__

In [32]:
arr_2D=np.array([5,10,15],[20,25,30],[35,40,45])

ValueError: only 2 non-keyword arguments accepted

ok note the error above its because 2D array should have [[]] in start and end as below

In [33]:
arr_2D=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [34]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
#grabbing items using double [] notation
#array[row][column]
arr_2D[0][0] #row 0 column0 =5

5

In [36]:
arr_2D[1] #entire row 1

array([20, 25, 30])

In [39]:
arr_2D[0][1] #row 0 column 1 =10

10

In [40]:
#grabbing items using single [] notation
#array[row,column]
arr_2D[0,0] #row 0 column 0=5

5

In [41]:
arr_2D[1]

array([20, 25, 30])

In [42]:
arr_2D[0,1]

10

slicing can grab column as [0] grabbed row 0

In [46]:
#all rows but column only 0(note again 1 is exclusive)
arr_2D[:,:1]

array([[ 5],
       [20],
       [35]])

__grab 25,30,40,45__

In [47]:
arr_2D[1:,1:] #rows from 1 to all column from 1 to all

array([[25, 30],
       [40, 45]])

__grab 20,25,35,40__

In [49]:
arr_2D[1:,0:2]

array([[20, 25],
       [35, 40]])

this is how sub section of an array can be selected

__conditional selection__

In [50]:
linear_arr=np.arange(1,11)

In [51]:
linear_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
cond_arr= linear_arr >6

In [53]:
cond_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

cond_arr becomes a bool for all >6 true rest false

In [54]:
#cond_arr can be passed to linear_arr
linear_arr[cond_arr]

array([ 7,  8,  9, 10])

In [55]:
linear_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

no difference to actual array. that was just a view

In [56]:
#can also be done as below
linear_arr[linear_arr<4]

array([1, 2, 3])

__select all the even items from linear_arr__

In [57]:
linear_arr[linear_arr%2==0]

array([ 2,  4,  6,  8, 10])

__select all the multiples of 3__

In [58]:
linear_arr[linear_arr%3==0]

array([3, 6, 9])

In [59]:
arr_2D[arr_2D>25]

array([30, 35, 40, 45])