__numpy operations__

__* array with array__

__* array with scalars__

__* universal array functions__

In [1]:
import numpy as np

In [3]:
arr=np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#array addition
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
#array subtraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#array multiplication
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
#array division
arr / arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

operations take place item by item i;e 1st item will be operated with 1st item and so on

__array to scalar__ does operation with every element to an scalar as below

In [9]:
#addition with scalar
arr + 100 #adds 100 to every element

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
#multiplication with scalar
arr *100 #multilpy 100 to every element

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [11]:
#subtraction
arr - arr #subtracts every element by itself

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr -100 #subtracts 100 by every element

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

now one thing to note is numpy gives an error to a mathmatical annomaly like zero division

In [14]:
arr=np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
1/0

ZeroDivisionError: integer division or modulo by zero

gives an error of division by 0

but in numpy array it throws a waring and code executes as below

In [17]:
arr / arr

/home/prashant/workspace/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
from __future__ import division

In [20]:
arr /arr

/home/prashant/workspace/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

throws a warning here in python 3 python 2 gives 0/0 as 0

now see below 1/arr

In [21]:
1/arr

/home/prashant/workspace/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

inf means infinity here 1/0 is infinity

__array with exponents__

In [22]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

gives you squares

__universal array functions:__ universal functions that broadcast accross every element

In [23]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [24]:
#exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [25]:
#max of array
np.max(arr)

10

In [29]:
#trigonometric functions sin cosin etc
print np.sin(arr)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


In [31]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [30]:
#log function
np.log(arr)

/home/prashant/workspace/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

log of 0 is -infinity so is the warning

check https://docs.scipy.org/doc/numpy/reference/ufuncs.html for universal functions

thats it for this book just make sure of warnings /0 ets